# Generated by Django 5.0.3 on 2024-04-07 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manga_table',
            options={'verbose_name': 'Манга', 'verbose_name_plural': 'Манга'},
        ),
    ]
